// ═══════════════════════════════════════
// BLUE NECK EVENTS — SITE CONSTANTS
// ═══════════════════════════════════════

export const SITE_CONFIG = {
  name: 'Blue Neck Events',
  tagline: 'Where Moments Become Legends',
  description: 'Premium event management crafting extraordinary experiences across weddings, corporate galas, concerts, and beyond.',
  email: 'hello@blueneckevents.com',
  phone: '+91 98765 43210',
  whatsapp: '+919876543210',
  address: 'Mumbai, Maharashtra, India',
  instagram: 'https://instagram.com/blueneckevents',
  facebook: 'https://facebook.com/blueneckevents',
  founded: 2015,
}

export const STATS = [
  { value: 850, suffix: '+', label: 'Events Crafted' },
  { value: 12, suffix: 'K+', label: 'Happy Guests' },
  { value: 9, suffix: '', label: 'Years of Excellence' },
  { value: 98, suffix: '%', label: 'Client Satisfaction' },
]

export const NAV_LINKS = [
  { label: 'Weddings', href: '/weddings' },
  { label: 'Corporate', href: '/corporate' },
  { label: 'Social Events', href: '/social' },
  { label: 'Birthdays', href: '/birthdays' },
  { label: 'Sports', href: '/sports' },
  {
    label: 'More',
    href: '#',
    children: [
      { label: 'Luxury Galas', href: '/galas' },
      { label: 'Product Launches', href: '/launches' },
      { label: 'Concerts & Shows', href: '/concerts' },
      { label: 'Destination Events', href: '/destinations' },
    ],
  },
  { label: 'Gallery', href: '/gallery' },
  { label: 'About', href: '/about' },
]

export const EVENT_CATEGORIES = [
  {
    id: 'weddings',
    label: 'Weddings',
    tagline: 'Your perfect day, flawlessly crafted',
    description: 'From intimate ceremonies to grand celebrations, we weave your love story into an unforgettable masterpiece.',
    href: '/weddings',
    color: '#E8D5B0',
    accentColor: '#C9A740',
    image: 'https://images.unsplash.com/photo-1519741349-a57a0f88d50a?auto=format&fit=crop&w=1200&q=80',
    icon: '💍',
  },
  {
    id: 'corporate',
    label: 'Corporate Events',
    tagline: 'Elevate your brand experience',
    description: 'Conferences, product launches, and award galas that leave a lasting impression on every attendee.',
    href: '/corporate',
    color: '#2A6BB0',
    accentColor: '#1A4A7A',
    image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80',
    icon: '🏢',
  },
  {
    id: 'social',
    label: 'Social Events',
    tagline: 'Celebrations worth remembering',
    description: 'Vibrant social gatherings, theme parties, and reunions that create memories for a lifetime.',
    href: '/social',
    color: '#C9A740',
    accentColor: '#F0C860',
    image: 'https://images.unsplash.com/photo-1514525253161-7a6c1cc1a1a6?auto=format&fit=crop&w=1200&q=80',
    icon: '🎉',
  },
  {
    id: 'birthdays',
    label: 'Birthday Parties',
    tagline: 'Every year, a grand celebration',
    description: 'Playful, joyful, and magical birthday experiences tailored for every age and personality.',
    href: '/birthdays',
    color: '#E8A0BF',
    accentColor: '#C97B8A',
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80',
    icon: '🎂',
  },
  {
    id: 'sports',
    label: 'Sports Events',
    tagline: 'Adrenaline meets excellence',
    description: 'Dynamic sports tournaments, marathons, and athletic events managed with precision and energy.',
    href: '/sports',
    color: '#40C940',
    accentColor: '#207A20',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    icon: '🏆',
  },
  {
    id: 'galas',
    label: 'Luxury Galas',
    tagline: 'Black-tie moments redefined',
    description: 'Award ceremonies, charity galas, and exclusive black-tie affairs with unmatched elegance.',
    href: '/galas',
    color: '#9B59B6',
    accentColor: '#6C3483',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80',
    icon: '🥂',
  },
  {
    id: 'launches',
    label: 'Product Launches',
    tagline: 'Unveil with impact',
    description: 'Brand reveals, store launches, and product unveilings that generate buzz and build legacy.',
    href: '/launches',
    color: '#E74C3C',
    accentColor: '#C0392B',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
    icon: '🚀',
  },
  {
    id: 'concerts',
    label: 'Concerts & Shows',
    tagline: 'Electrify the night',
    description: 'Live music events, entertainment nights, and large-scale performances that captivate thousands.',
    href: '/concerts',
    color: '#3498DB',
    accentColor: '#1A6BA6',
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=1200&q=80',
    icon: '🎸',
  },
  {
    id: 'destinations',
    label: 'Destination Events',
    tagline: 'The world as your venue',
    description: 'Exotic destination weddings and events in Goa, Dubai, Bali, Maldives, and beyond.',
    href: '/destinations',
    color: '#1ABC9C',
    accentColor: '#148F77',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    icon: '✈️',
  },
]

export const TESTIMONIALS = [
  {
    name: 'Priya & Arjun Mehta',
    event: 'Wedding — Udaipur',
    quote: 'Blue Neck Events turned our dream wedding into a reality that exceeded every expectation. The attention to detail was simply breathtaking.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
  },
  {
    name: 'Rajesh Kumar',
    event: 'Corporate Summit — Mumbai',
    quote: 'Our annual summit was transformed into a world-class experience. Every guest was in awe. Blue Neck delivered beyond our briefing.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
  {
    name: 'Ananya Sharma',
    event: 'Birthday Gala — Delhi',
    quote: 'My 40th birthday felt like a Hollywood production. The themes, the décor, the flow — absolute perfection from start to finish.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80',
  },
  {
    name: 'Tech Innovations Ltd.',
    event: 'Product Launch — Bangalore',
    quote: 'Our iPhone-level product launch event created national buzz. Blue Neck understood our brand DNA perfectly.',
    rating: 5,
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
  },
]

export const GALLERY_IMAGES = [
  {
    id: 1,
    src: 'https://images.unsplash.com/photo-1519741349-a57a0f88d50a?auto=format&fit=crop&w=800&q=80',
    category: 'weddings',
    title: 'Golden Hour Ceremony',
    cols: 2,
    rows: 2,
  },
  {
    id: 2,
    src: 'https://images.unsplash.com/photo-1583939003579-fe5ee0fcabb3?auto=format&fit=crop&w=800&q=80',
    category: 'weddings',
    title: 'Floral Mandap',
    cols: 1,
    rows: 1,
  },
  {
    id: 3,
    src: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=800&q=80',
    category: 'corporate',
    title: 'Executive Summit',
    cols: 1,
    rows: 2,
  },
  {
    id: 4,
    src: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
    category: 'galas',
    title: 'Awards Night',
    cols: 2,
    rows: 1,
  },
  {
    id: 5,
    src: 'https://images.unsplash.com/photo-1514525253161-7a6c1cc1a1a6?auto=format&fit=crop&w=800&q=80',
    category: 'social',
    title: 'Neon Celebration',
    cols: 1,
    rows: 1,
  },
  {
    id: 6,
    src: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=800&q=80',
    category: 'concerts',
    title: 'Live Concert',
    cols: 2,
    rows: 2,
  },
  {
    id: 7,
    src: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80',
    category: 'birthdays',
    title: 'Grand Birthday',
    cols: 1,
    rows: 1,
  },
  {
    id: 8,
    src: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80',
    category: 'destinations',
    title: 'Beachfront Event',
    cols: 1,
    rows: 2,
  },
  {
    id: 9,
    src: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
    category: 'launches',
    title: 'Brand Reveal',
    cols: 2,
    rows: 1,
  },
  {
    id: 10,
    src: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
    category: 'sports',
    title: 'Championship Event',
    cols: 1,
    rows: 1,
  },
]

export const TEAM_MEMBERS = [
  {
    name: 'Vikram Nair',
    role: 'Founder & Creative Director',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    bio: '15 years of transforming visions into extraordinary experiences.',
  },
  {
    name: 'Sneha Kapoor',
    role: 'Head of Design & Décor',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    bio: 'Award-winning designer with a passion for immersive environments.',
  },
  {
    name: 'Aryan Desai',
    role: 'Operations Director',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80',
    bio: 'Precision-driven logistics expert who ensures flawless execution.',
  },
  {
    name: 'Riya Malhotra',
    role: 'Client Experience Lead',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80',
    bio: 'Dedicated to turning every client dream into absolute reality.',
  },
]
